resources:
- name: repo
  type: git
  check_every: 1m
  icon: github
  source:
    uri: ((repo.url))
    branch: ((repo.branch))
    ignore_paths:
    - ci/
- name: ci-repo
  type: git
  check_every: 1m
  icon: github
  source:
    uri: ((repo.url))
    branch: ((repo.branch))
    paths:
    - ci/

jobs:
# - name: set-pipeline
#   plan:
#   - get: ci-repo
#     params:
#       submodules: none
#     trigger: true
#   - set_pipeline: self
#     file: ci-repo/ci/images/pipeline.yml
#     var_files:
#     - ci-repo/ci/images/pipeline.vars.yml

- name: test
  plan:
  - in_parallel:
    - get: ci-repo
      params:
        submodules: none
    - get: repo
  - in_parallel:
    - task: get-cloudgate-creds
      file: ci-repo/ci/tasks/get-cloudgate-creds/task.yml
      params:
        CLOUDGATE_BASE_URL: https://api.console.cloudgate.vmware.com
        CLOUDGATE_CLIENT_ID: ((ci/cloudgate.clientId))
        CLOUDGATE_CLIENT_SECRET: ((ci/cloudgate.clientSecret))
        CLOUDGATE_MASTER_ACCOUNT_ID: ((ci/cloudgate.masterAccountId))
        CLOUDGATE_ORG_ACCOUNT_ID: ((ci/cloudgate.orgAccountId))
        CLOUDGATE_OU_ID: ((ci/cloudgate.ouId))
        CLOUDGATE_TTL: 43200
    - task: generate-taskcat-config
      file: ci-repo/ci/tasks/taskcat-generate-config/task.yml
      params:
        VAR_tanzunet_username: ((ci/tanzunet.username))
        VAR_tanzunet_password: ((ci/tanzunet.password))
        VAR_tanzunet_refreshToken: ((ci/tanzunet.refreshToken))
        VAR_keypairName: ((ci/qs-test/keypair.name))
        VAR_bucket: tcat-9d0156f41d3b503b8360120b8214b6f1
        VAR_domain: thingamaji.ga

  - task: taskcat-upload
    file: ci-repo/ci/tasks/taskcat-build-upload/task.yml
    params:
      NIMBUS_USER: ((ci/nimbus.user))
      NIMBUS_DEPLOY_OPTS: '--cpus=6 --memory=4096'
      DOCKER_HUB_PROXY: ((dockerhub-proxy))

  - task: taskcat-test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: tappc-docker-local.artifactory.eng.vmware.com/ci/docker-image
          tag: latest
      inputs:
      - name: taskcat-config
      - name: repo
      - name: creds
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          set -u
          set -o pipefail

          source creds/env.inc.sh

          cd repo
          taskcat --debug \
            test run \
              --skip-upload \
              --input-file ../taskcat-config/taskcat.yml \
              --test-names single \
              --minimal-output
