---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: tappc-docker-local.artifactory.eng.vmware.com/ci/docker-image
    tag: latest
inputs:
- name: creds
- name: ci-repo
params:
  REGIONS: us-east-1
run:
  path: ci-repo/ci/tasks/aws-housekeeping/stacks.sh
