---
platform: linux
inputs:
- name: ci-repo
- name: creds
- name: repo
outputs:
- name: output
caches:
- path: image-cache
params:
  NIMBUS_USER:
  NIMBUS_DEPLOY_OPTS:
  DOCKER_HUB_PROXY:
  RUN: 'echo >&2 "RUN not defined. Exiting."; exit 1;'
run:
  path: execute
  args:
  - "bash"
  - "-euo"
  - "pipefail"
  - "-c"
  - "$RUN"
